# kohya_ss — Flux 2 Dev LoRA Training Config (AAA Quality)
# Run on RunPod A40/L40S (48GB VRAM)
#
# Usage:
#   cd traindata && bash train_kohya.sh
#
# Key settings for maximum face fidelity:
#   rank 64 (high capacity), alpha 32 (rank/2 for stability)
#   lr 1e-4, cosine_with_restarts, 2200 steps
#   22 images × 5 repeats × 2200 steps ≈ full coverage

job: extension
config:
  name: mgnperson_flux2_lora_v2
  process:
    - type: sd_trainer
      training_folder: output/mgnperson_flux2_v2
      device: cuda:0
      trigger_word: MGNPERSON

      network:
        type: lora
        linear: 64          # LoRA rank — high for face fidelity
        linear_alpha: 32    # alpha = rank/2 for stable training

      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 3

      datasets:
        - folder_path: traindata/images
          caption_ext: txt
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution:
            - 512
            - 768
            - 1024

      train:
        batch_size: 2
        steps: 2200
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: flowmatch
        optimizer: adamw8bit
        lr: 1e-4
        lr_scheduler: cosine_with_restarts
        lr_scheduler_params:
          T_max: 2200
          eta_min: 1e-6

      model:
        name_or_path: black-forest-labs/FLUX.2-dev
        is_flux: true
        quantize: true     # fp8 base model for memory efficiency

      sample:
        sampler: flowmatch
        sample_every: 500
        width: 1024
        height: 1024
        prompts:
          - "A photorealistic close-up portrait of MGNPERSON, a young Turkish woman with dark brown wavy bob-length hair and warm brown eyes, wearing a cream knit sweater, soft smile, natural window light, shallow depth of field, clean background"
          - "A photorealistic full body photograph of MGNPERSON, a young Turkish woman, wearing a black leather jacket and blue jeans, confident pose, urban street background, golden hour light"
          - "A photorealistic portrait of MGNPERSON, a young Turkish woman with dark brown wavy hair, laughing genuinely with eyes crinkled, wearing a white blouse, soft studio lighting"
